### ISSUE TITLE
Automatically install ubuntu

### ISSUE THREAD

**Issue by quangvi282** [netson/ubuntu-unattended#11]
I can't get auto install ubuntu when i boot ubuntu unattend that created by script.

**Comment by netson** [comment]
Do you get any error message? Please provide me with some more info, otherwise it'll be near impossible to determine what's going on.

**Comment by quangvi282** [comment]
no error message, i got ubuntu- unattended  but when boot on usb , it no
have option auto install ubuntu

2016-05-22 19:52 GMT+07:00 netson notifications@github.com:

> Do you get any error message? Please provide me with some more info,
> otherwise it'll be near impossible to determine what's going on.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/netson/ubuntu-unattended/issues/11#issuecomment-220830848

## 

_Thanks and Best Regards,_

_Trịnh Quang Vỉ_

**Comment by netson** [comment]
Could you maybe post a screenshot and describe in more detail which steps you took to reproduce your issue? Are you sure you are booting from the right device with the right image?
