### ISSUE TITLE
Ubuntu desktop support?

### ISSUE THREAD

**Issue by incrazyboyy** [netson/ubuntu-unattended#18]
Hi there,
I'm looking for an easier method to install Ubuntu 16 on computers in my office. This project looks like the perfect soloution, but your description says that it only supports Ubuntu Server "out of the box".
So the question is if it's possible to create an unattended Ubuntu desktop installation?

**Comment by netson** [comment]
Check out this tool for ubuntu Desktop: https://apps.ubuntu.com/cat/applications/precise/uck/
