### ISSUE TITLE
installation of Ubuntu 16.04 crashes

### ISSUE THREAD

**Issue by moozzer** [netson/ubuntu-unattended#21]
I get the following error when installing the unattended version:

http://imgur.com/awYT2ju

I just used the provided bash script and did not changed one thing. I used the image in VMware ESXI. The 16.04 version. I hope this helps :)

Update:

This problem is present in version 16.04 and 16.04.1, the 14.04 version does work

**Comment by skorzhevsky** [comment]
Fixed, sent a PR.
