### ISSUE TITLE
Desktop like load screen?

### ISSUE THREAD

**Issue by tylerhammer** [netson/ubuntu-unattended#27]
Any idea why when I use the script to create an installation and use the preseed, I get this load screen? https://i.cyanlab.io/YmMwNWNk.png

Also as a side note, any idea why I get a yellow bash when using the preseed script?

**Comment by jmcgeheeiv** [comment]
The linked PNG file no longer exists; "yellow bash" is unclear.  Perhaps this issue should be closed?
