### ISSUE TITLE
Boot hangs after install on KVM

### ISSUE THREAD

**Issue by Dhull442** [netson/ubuntu-unattended#34]
I tried to install the unattended iso file created using the script in a KVM virtual machine.
Everything goes fine during the install, but the machine hangs on the first boot after install. The same problem doesn't happen when I install the standard server iso file. Also, the same unattended iso file works fine with VirtualBox. I first thought the error might be due to some intel_rapl message at the beginning, but it's not.

**Comment by netson** [comment]
Any chance you are able to make a screenshot via console or something of what the boot seems to be stuck on?

**Comment by Dhull442** [comment]
There was a blank screen opening up in the front which I was able to close using Alt+F4 and all the commands and everything was actually working in the background. So the issue is not actually due to preseeding and was probably due to difference in VM settings set during the creation.
