### ISSUE TITLE
failed to run preseeded command / wget

### ISSUE THREAD

**Issue by tenox7** [netson/ubuntu-unattended#35]
ubuntu-16.04.4-server-amd64-unattended.iso is failing to complete unattended install with this error message:

![image](https://user-images.githubusercontent.com/8151602/43185892-0e03c260-8fa2-11e8-824b-91fe28fb039a.png)

**Comment by tenox7** [comment]
The url should be:
https://raw.githubusercontent.com/netson/ubuntu-unattended/master/start.sh

**Comment by tenox7** [comment]
changing the path is not enough I still get the error even with correct path, I think wget is missing in the target

**Comment by tenox7** [comment]
changed from wget to curl and now it works

**Comment by netson** [comment]
Thanks for the PR, merged and closing now
