### ISSUE TITLE
Not working on Hyper-V Gen 2

### ISSUE THREAD

**Issue by yuna0327** [netson/ubuntu-unattended#4]
Hello.
Awesome script, its working perfect but on hyper-v only on Gen 1

Scenario
Gen 2 - disabled secure boot, boot from CD -> cannot boot and it will try to boot from network (defaul ubuntu doesn't have problem)

**Comment by netson** [comment]
Hey, thanks for the feedback! Unfortunately, I do not use Hyper-V, nor do I have something to test that on. Were you able to find what the problem is? If so, then maybe I can apply a patch so the script works for Hyper-V as well.

Let me know!
