### ISSUE TITLE
Illegal sed command on MacOS

### ISSUE THREAD

**Issue by luketainton** [netson/ubuntu-unattended#41]
Ubuntu is not downloaded due to an illegal sed option. See script output:

 +---------------------------------------------------+
 |            UNATTENDED UBUNTU ISO MAKER            |
 +---------------------------------------------------+

create-unattended-iso.sh: line 63: lsb_release: command not found
 which ubuntu edition would you like to remaster:

  [1] Ubuntu 12.04.5 LTS Server amd64 - Precise Pangolin
  [2] Ubuntu 14.04.5 LTS Server amd64 - Trusty Tahr
  [3] Ubuntu 16.04.6 LTS Server amd64 - Xenial Xerus
  [4] Ubuntu 18.04.2 LTS Server amd64 - Bionic Beaver

 please enter your preference: [1|2|3|4]: 4
 please enter your preferred timezone: Europe/London
 please enter your preferred username: user
 please enter your preferred password:
 confirm your preferred password:
 Make ISO bootable via USB: yes
 downloading ubuntu-18.04.2-server-amd64.iso:     sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

**Comment by netson** [comment]
Hi, thanks for the report; however, since I do not own/use any MacOS device, it's difficult for me to test this. I assume it is because the versions of SED on Ubuntu and MacOS are different and/or support different parameters? Maybe you can confirm this by checking the manpage on MacOS for your SED version?

According to the regular manpage, this is what the -u flag does:
`-u, --unbuffered
load minimal amounts of data from the input files and flush the output buffers more often`

**Comment by atwright147** [comment]
@luketainton

Try using `brew` to install the GNU version of `sed`:

```sh
# find out about gnu sed
brew info gnu-sed

# install gnu sed
brew install gnu-sed
```

Looks like you will need to add `PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"` to your bashrc or zshrc file to get it to work.

**Comment by luketainton** [comment]
I'll look into this when I have some time and get back to you. Thanks for the suggestion!

**Comment by luketainton** [comment]
@atwright147 I installed gnu-sed which did advance the script, but there are still issues:

` +---------------------------------------------------+
 |            UNATTENDED UBUNTU ISO MAKER            |
 +---------------------------------------------------+

create-unattended-iso.sh: line 63: lsb_release: command not found
 which ubuntu edition would you like to remaster:

  [1] Ubuntu 12.04.5 LTS Server amd64 - Precise Pangolin
  [2] Ubuntu 14.04.6 LTS Server amd64 - Trusty Tahr
  [3] Ubuntu 16.04.6 LTS Server amd64 - Xenial Xerus
  [4] Ubuntu 18.04.2 LTS Server amd64 - Bionic Beaver

 please enter your preference: [1|2|3|4]: 4
 please enter your preferred timezone: /var/db/timezone/zoneinfo/Europe/London
 please enter your preferred username: netson
 please enter your preferred password:
 confirm your preferred password:
 Make ISO bootable via USB: yes
 downloading netson.seed:     sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
 DONE
 installing required packages
create-unattended-iso.sh: line 168: lsb_release: command not found
 remastering your iso file
create-unattended-iso.sh: line 194: /Users/luke/iso_new/isolinux/lang: No such file or directory
sed: /Users/luke/iso_new/isolinux/isolinux.cfg: No such file or directory
cp: illegal option -- T
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
create-unattended-iso.sh: line 214: /Users/luke/iso_new/preseed/netson.seed: No such file or directory
create-unattended-iso.sh: line 217: mkpasswd: command not found
sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
create-unattended-iso.sh: line 228: md5sum: command not found
sed: 1: "/Users/luke/iso_new/iso ...": extra characters at the end of l command
 creating the remastered iso
create-unattended-iso.sh: line 243: isohybrid: command not found
umount: /Users/luke/iso_org: not currently mounted
 -----
 finished remastering your ubuntu iso file
 the new file is located at: /Users/luke/ubuntu-18.04.2-server-amd64-unattended.iso
 your username is: netson
 your password is: netson
 your hostname is: ubuntu
 your timezone is: /var/db/timezone/zoneinfo/Europe/London`

**Comment by luketainton** [comment]
@atwright147 I did as you said, and while it did advance the script, there are still issues.

>  +---------------------------------------------------+
>  |            UNATTENDED UBUNTU ISO MAKER            |
>  +---------------------------------------------------+
> 
> create-unattended-iso.sh: line 63: lsb_release: command not found
>  which ubuntu edition would you like to remaster:
> 
>   [1] Ubuntu 12.04.5 LTS Server amd64 - Precise Pangolin
>   [2] Ubuntu 14.04.6 LTS Server amd64 - Trusty Tahr
>   [3] Ubuntu 16.04.6 LTS Server amd64 - Xenial Xerus
>   [4] Ubuntu 18.04.2 LTS Server amd64 - Bionic Beaver
> 
>  please enter your preference: [1|2|3|4]: 4
>  please enter your preferred timezone: /var/db/timezone/zoneinfo/Europe/London
>  please enter your preferred username: netson
>  please enter your preferred password:
>  confirm your preferred password:
>  Make ISO bootable via USB: yes
>  downloading netson.seed:     sed: illegal option -- u
> usage: sed script [-Ealn] [-i extension] [file ...]
>        sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
>  DONE
>  installing required packages
> create-unattended-iso.sh: line 168: lsb_release: command not found
>  remastering your iso file
> create-unattended-iso.sh: line 194: /Users/luke/iso_new/isolinux/lang: No such file or directory
> sed: /Users/luke/iso_new/isolinux/isolinux.cfg: No such file or directory
> cp: illegal option -- T
> usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
>        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
> create-unattended-iso.sh: line 214: /Users/luke/iso_new/preseed/netson.seed: No such file or directory
> create-unattended-iso.sh: line 217: mkpasswd: command not found
> sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
> sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
> sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
> sed: 1: "/Users/luke/iso_new/pre ...": extra characters at the end of l command
> create-unattended-iso.sh: line 228: md5sum: command not found
> sed: 1: "/Users/luke/iso_new/iso ...": extra characters at the end of l command
>  creating the remastered iso
> create-unattended-iso.sh: line 243: isohybrid: command not found
> umount: /Users/luke/iso_org: not currently mounted
>  -----
>  finished remastering your ubuntu iso file
>  the new file is located at: /Users/luke/ubuntu-18.04.2-server-amd64-unattended.iso
>  your username is: netson
>  your password is: netson
>  your hostname is: ubuntu
>  your timezone is: /var/db/timezone/zoneinfo/Europe/London

**Comment by atwright147** [comment]
Did you do this bit:

> Looks like you will need to add PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH" to your bashrc or zshrc file to get it to work.

It looks like you are getting exactly the same error as before.

**Comment by luketainton** [comment]
I did do that but for some reason it was still using the built-in version of sed. I've created a symbolic link to where the MacOS version of sed is - I'll try again and see what happens.

**Comment by atwright147** [comment]
Also, try adding an `echo $PATH` to the script to see what path the script is running with.

I did this on a Mac and I don't remember having these issues but I can't remember if maybe I did it in a VM. That might be an option for you, create a VM in VirtualBox and then run this script from within that

**Comment by luketainton** [comment]
That might be the easiest option. The script is also calling `lsb_release` which is not available on MacOS, which is making me think that the script isn't fully portable to MacOS.

Thanks for your help @atwright147 !
