### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by whittinghamj** [netson/ubuntu-unattended#42]
+---------------------------------------------------+
 |            UNATTENDED UBUNTU ISO MAKER            |
 +---------------------------------------------------+

 which ubuntu edition would you like to remaster:

  [1] Ubuntu href="precise/" LTS Server amd64 - Precise Pangolin
  [2] Ubuntu href="trusty/" LTS Server amd64 - Trusty Tahr
  [3] Ubuntu href="xenial/" LTS Server amd64 - Xenial Xerus
  [4] Ubuntu href="bionic/" LTS Server amd64 - Bionic Beaver

 please enter your preference: [1|2|3|4]: 4
 please enter your preferred timezone: Etc/UTC
 please enter your preferred username: whittinghamj
 please enter your preferred password: 
 confirm your preferred password: 
 Make ISO bootable via USB: yes
 downloading ubuntu-href="bionic/"-server-amd64.iso: 11:52: DONE
Error: Failed to download ISO: http://cdimage.ubuntu.com/releases/href="bionic/"/release/ubuntu-href="bionic/"-server-amd64.iso
This file may have moved or may no longer exist.

You can download it manually and move it to /root/ubuntu-href="bionic/"-server-amd64.iso
Then run this script again.

Any ideas?

**Comment by hoanganh25991** [comment]
Ubuntu change urls, which cause the problems:

- http://releases.ubuntu.com/
- http://cdimage.ubuntu.com/releases

Script `create-unattended-iso.sh` run through:
- line [74-77](https://github.com/netson/ubuntu-unattended/blob/master/create-unattended-iso.sh#L74): Get wrong name
- line [92-107](https://github.com/netson/ubuntu-unattended/blob/master/create-unattended-iso.sh#L92): Get wrong download link

You may work around as hard-code download link. Ex:

For ubuntu 18.04

```sh
[4]* )  download_file="ubuntu-18.04.2-server-amd64.iso"
           download_location="http://cdimage.ubuntu.com/releases/18.04/release/"
           new_iso_name="ubuntu-18.04.2-server-amd64-unattended.iso"
           break;;
```

**Comment by netson** [comment]
Or if the change is for all images, you could just change the main download URL in the script; if you do, please submit a PR and I will merge it into the main script!
