### ISSUE TITLE
Change configuration for Ubuntu server address

### ISSUE THREAD

**Issue by ghost** [netson/ubuntu-unattended#47]
Bionic address shouldn't be:
`http://cdimage.ubuntu.com/releases/release/ubuntu-server-amd64.iso`

It should be:
`http://cdimage.ubuntu.com/releases/18.04.3/release/ubuntu-18.04.3-server-amd64.iso`

**Comment by lmckiwo** [comment]
The following pull request addresses this issue: https://github.com/netson/ubuntu-unattended/pull/49

**Comment by netson** [comment]
PR #49 merged, so should be fixed now!
