### ISSUE TITLE
Request: luks encryption option

### ISSUE THREAD

**Issue by runultra** [netson/ubuntu-unattended#48]
This may be the wrong way to go about it, but is there any option that could create a luks encryption unattended installer?

**Comment by netson** [comment]
It's been a while since I ran a manual installation, but if the default installer provides an option for it (I believe it does for the home directory?), then it should be possible and a matter of getting the right questions answered. If not, you would need to use a postinstall task of some sort.

**Comment by rotflol** [comment]
changing  
partman-auto/method                                     string      lvm
to
partman-auto/method                                     string      crypto
in 
netson.seed
will enable luks encryption
