### ISSUE TITLE
New menu build pulls in live isos

### ISSUE THREAD

**Issue by rotflol** [netson/ubuntu-unattended#51]
the exclude list (line 79) should be extended with |live
at line 91 the exclude list should be added
 line 91: wget -qO - ${URL} | grep server | grep amd64 | egrep -v ${EXLCUDE_LIST} >/dev/null

**Comment by lmckiwo** [comment]
The reason why "live" wasn't included is because in later releases, i see that live and servers are under the same iso file.

**Comment by rotflol** [comment]
the live isos dont work with this preseeding!

**Comment by lmckiwo** [comment]
@rotflol  I retested and you are correct.  For some odd reason when i tested, it seem like it was working.  Correction on its way.
