### ISSUE TITLE
timezone has .. prefix

### ISSUE THREAD

**Issue by lmckiwo** [netson/ubuntu-unattended#52]
this is because on my machine, the softlink is as follows:
lrwxrwxrwx. 1 root root 38 Jan 14 09:01 /etc/localtime -> ../usr/share/zoneinfo/America/New_York

so this causes the default answer in the prompt to be as follows:
 please enter your preferred timezone: ..America/New_York

**Comment by netson** [comment]
I'm gonna close this issue, as it seems the sed command to fetch the timezone already fixes this. If not, please feel free to reopen! :-)
