### ISSUE TITLE
Source code origin question

### ISSUE THREAD

**Issue by MichaelZaidman** [netson/ubuntu-unattended#58]
Hi Rinck,

I encountered the same code, at least in its initial form, released in the same year but under the GPL3 license - https://github.com/hvanderlaan/ubuntu-unattended

The only trace to your work is a comment in the script "# copy the netson seed file to the iso", while the seed file is named differently. Wondering what is the netson seed, I found your repository. It looks like your repository was the origin of the hvanderlaan repository but I do not see any credits in his repository... Can you please comment? 

Thanks,
Michael

**Comment by netson** [comment]
Hi Michael,

the source is indeed mine originally (excluding all the great pull requests I have received and merged over the years) so a reference to this repository would seem like the right thing to do for @hvanderlaan .

As for the seed file you are referring to, this is https://github.com/netson/ubuntu-unattended/blob/master/netson.seed and is a file which contains all the answers to the questions asked during install.

Hope that helps!

Regards,
Rinck
