### ISSUE TITLE
Repair pls. -"grep -w DIR |"

### ISSUE THREAD

**Issue by deviantdev** [netson/ubuntu-unattended#59]
https://github.com/netson/ubuntu-unattended/blob/204dbfac2ef773fe78aaaac9e40f33e6c776a655/create-unattended-iso.sh#L86

`for version in $(wget -qO - http://cdimage.ubuntu.com/releases/ | grep -w DIR | grep -oP href=\"[0-9].* | cut -d'"' -f2 | tr -d '/'); do`

to

 `for version in $(wget -qO - http://cdimage.ubuntu.com/releases/ | grep -oP href=\"[0-9].* | cut -d'"' -f2 | tr -d '/'); do`

**Comment by lmckiwo** [comment]
Thanks for the fix.  I will do a pull requests in a couple of hours.

**Comment by lmckiwo** [comment]
Please close issue.
